# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
configfile: "config/config.yaml"
configfile: "config/private-config.yaml"
# Define variables from configuration file
DEFAULT_DEST_FILEPATH = config.get("DEFAULT_DEST_FILEPATH", "results/")
RENAMED_READS_FILEPATH = config.get("RENAMED_READS_FILEPATH","renamed_raw_reads")
RRNA_FILEPATH = config.get("RRNA_FILEPATH","rrna/")
METARIB_FILEPATH = config.get("METARIB_FILEPATH", "MetaRib/")

# Define available threads
AVAILABLE_THREADS = int(workflow.cores * 0.75)
# Define global wildcards for input data after renaming
regex_raw_illumina_files = (
    f"{DEFAULT_DEST_FILEPATH}{RENAMED_READS_FILEPATH}{{sample}}_{{read}}.fastq.gz"
)
sample, read = glob_wildcards(regex_raw_illumina_files)
unique_samples = set(sample)
# Define rule all
rule all:
    input: 
        f"{DEFAULT_DEST_FILEPATH}{METARIB_FILEPATH}MetaRib",
        expand(
            f"{DEFAULT_DEST_FILEPATH}{METARIB_FILEPATH}data/all.{{direction}}.fq",
            direction = ["1", "2"]
        )
# Include rules
include: "rules/rename.smk"
include: "rules/trim_galore.smk"
include: "rules/sortmerna.smk"
include: "rules/metarib.smk"