import pandas as pd
from pathlib import Path
import re

from targets.qc import qc_outputs
#from workflow.targets.rna import rna_outputs
#from workflow.targets.rrna import rrna_outputs

configfile: "config/config.yaml"

# --------------------------
# Load samplesheet
# --------------------------…
samplesheet = pd.read_csv(
    config["samples_file"],
    sep=r"\s+",
    dtype=str,
    engine="python"
)

samplesheet.columns = samplesheet.columns.str.strip()
samplesheet = samplesheet.set_index("sample_id")

SAMPLES = samplesheet.index.tolist()

RESULTS_DIR = Path(config["shared_results_dir"])

NO_SAMPLES = len(SAMPLES)

print(f"{NO_SAMPLES} samples loaded")
print(f"Shared results directory: {RESULTS_DIR}")

# --------------------------
# Helpers
# --------------------------

def get_reads(sample):
    files = samplesheet.loc[sample, "input_files"].split(",")

    r1_patterns = ["_R1", "_1", "read1", "_forward"]
    r2_patterns = ["_R2", "_2", "read2", "_reverse"]

    r1 = None
    r2 = None

    for f in files:
        fname = Path(f).name.lower()

        if any(p.lower() in fname for p in r1_patterns):
            r1 = f
        elif any(p.lower() in fname for p in r2_patterns):
            r2 = f

    # fallback: assume order if detection failed
    if r1 is None or r2 is None:
        raise ValueError(
            f"[ERROR] Could not detect R1/R2 for sample '{sample}' from files: {files}"
        )

    return r1, r2

def raw_r1(wc):
    r1 = get_reads(wc.sample)[0]
    print(f"[INFO] {wc.sample}: R1={r1}")

    return r1

def raw_r2(wc):
    r2 = get_reads(wc.sample)[1]
    print(f"[INFO] {wc.sample}: R2={r2}")

    return r2

def sample_qc_dir(wc):
    return RESULTS_DIR / "qc" / wc.sample

def rrna_dir(*paths):
    return str(Path(RESULTS_DIR, "rRNA", *paths))

# --------------------------
# sortmeRNA stage logic
# --------------------------

def sortmerna_stages():
    """
    ['ssu', 'lsu'] -> ['ssu', 'ssu_lsu']
    """
    base = config["RNA"]["sortmerna_staged"]["pipeline"]
    return ["_".join(base[:i + 1]) for i in range(len(base))]

SORTMERNA_STAGES = sortmerna_stages()

PREVIOUS_STAGE = {
    SORTMERNA_STAGES[0]: "decontamination",
    **{
        SORTMERNA_STAGES[i]: SORTMERNA_STAGES[i - 1]
        for i in range(1, len(SORTMERNA_STAGES))
    },
}

FIRST_SORTMERNA_STAGE = [SORTMERNA_STAGES[0] for i in range(len(SAMPLES))]
FINAL_SORTMERNA_STAGE = [SORTMERNA_STAGES[-1] for i in range(len(SAMPLES))]

FIRST_STAGE_NAME = SORTMERNA_STAGES[0]
FINAL_STAGE_NAME = SORTMERNA_STAGES[-1]

print(f"sortmerna stages {SORTMERNA_STAGES} with previous stages {PREVIOUS_STAGE} and final stage {FINAL_SORTMERNA_STAGE} to be requested to trigger previous stages in the workflow")
# sortmerna stages ['ssu', 'ssu_lsu'] with previous stages {'ssu': 'decontamination', 'ssu_lsu': 'ssu'} with final stages being identical ['ssu_lsu', 'ssu_lsu'] for the samples

# --------------------------
# sortmeRNA helper paths
# --------------------------

def sortmerna_r1(wc):
    qc_base = RESULTS_DIR / "qc" / wc.sample
    rna_base = RESULTS_DIR / "RNA" / wc.sample

    prev = PREVIOUS_STAGE[wc.stage]

    if prev == "decontamination":
        return str(
            qc_base/"decontamination"/f"{wc.sample}_R1.cleaned.fastq.gz"
        )

    return str(
        rna_base/"sortmerna"/prev/f"{wc.sample}_{prev}.nonaligned_fwd.fq.gz"
    )

def sortmerna_r2(wc):
    qc_base = RESULTS_DIR / "qc" / wc.sample
    rna_base = RESULTS_DIR / "RNA" / wc.sample

    prev = PREVIOUS_STAGE[wc.stage]

    if prev == "decontamination":
        return str(
            qc_base / "decontamination" / f"{wc.sample}_R2.cleaned.fastq.gz"
        )

    return str(
        rna_base / "sortmerna" / prev / f"{wc.sample}_{prev}.nonaligned_rev.fq.gz"
    )

def sortmerna_db(wc):
    key = wc.stage.split("_")[-1]
    return config["databases"][f"sortmeRNA_{key}"]

def sortmerna_db_idx(wc):
    key = wc.stage.split("_")[-1]
    return config["databases"][f"sortmeRNA_{key}_idx"]

def RNA_separation_module():
    method = config["RNA"]["method"]
    refinement = config["RNA"]["refinement"]

    print(f"[RNA separation] method={method}, refinement={refinement}")

    outputs = []
    if method == "sortmerna":
        if refinement == "staged":
            outputs += expand(
                    f"{RESULTS_DIR}/RNA/{{sample}}/sortmerna/{{stage}}/{{sample}}_{{stage}}.aligned_fwd.fq.gz",
                    zip,
                    sample=SAMPLES,
                    stage=FINAL_SORTMERNA_STAGE,
                    )
            outputs += expand(
                    f"{RESULTS_DIR}/rRNA/{{sample}}/filtered/{{sample}}_rRNA_1.fastq.gz",
                    sample=SAMPLES,
                )
            outputs += expand(
                    f"{RESULTS_DIR}/nonrRNA/{{sample}}/filtered/{{sample}}_nonrRNA_1.fastq.gz",
                    sample=SAMPLES,
                )
            return outputs
        elif refinement == "combined":
            outputs += expand(
                    f"{RESULTS_DIR}/RNA/{{sample}}/sortmerna/aligned/{{sample}}_ssu_lsu.aligned.sam",
                    sample=SAMPLES,
                )
            outputs += expand(
                    f"{RESULTS_DIR}/RNA/{{sample}}/sortmerna/aligned/{{sample}}_SSU_filtered_taxonomy.tsv",
                    sample=SAMPLES,
                )
            # final filtered outputs
            outputs += expand(
                f"{RESULTS_DIR}/rRNA/{{sample}}/filtered/{{sample}}_rRNA_1.fastq.gz",
                sample=SAMPLES,
            )
            outputs += expand(
                f"{RESULTS_DIR}/nonrRNA/{{sample}}/filtered/{{sample}}_nonrRNA_1.fastq.gz",
                sample=SAMPLES,
            )
            return outputs
    elif method == "ribodetector": #consider bbduk, bbmap, alignments (bwa) or kraken2 classification as refinement steps
        outputs += expand(
            f"{RESULTS_DIR}/RNA/{{sample}}/ribodetector/{{sample}}_rRNA_1.fastq.gz",
            zip,
            sample=SAMPLES,
        )
        outputs += expand(
            f"{RESULTS_DIR}/nonrRNA/{{sample}}/filtered/{{sample}}_nonrRNA_1.fastq.gz",
            sample=SAMPLES,
        )
        if refinement == "bbduk":
            outputs += expand(
                f"{RESULTS_DIR}/rRNA/{{sample}}/filtered/{{sample}}_rRNA_1.fastq.gz",
                sample=SAMPLES,
            )
        return outputs
    elif method == "bbmap": #consider bbduk, bbmap, alignments (bwa) or kraken2 classification as refinement steps
        outputs += expand(
            f"{RESULTS_DIR}/RNA/{{sample}}/bbmap/{{sample}}_all_reads.bam",
            zip,
            sample=SAMPLES,
        )
        outputs += expand(
            f"{RESULTS_DIR}/rRNA/{{sample}}/filtered/{{sample}}_rRNA_1.fastq.gz",
            sample=SAMPLES,
        )
        outputs += expand(
            f"{RESULTS_DIR}/nonrRNA/{{sample}}/filtered/{{sample}}_nonrRNA_1.fastq.gz",
            sample=SAMPLES,
        )
        return outputs
    else:
        raise ValueError(f"Unsupported RNA method: {method}")

# --------------------------
# rRNA composition classification
# --------------------------

def rRNA_composition_method():
    method = config["rRNA"]["method"]
    print(f"RNA separation method: {method}")
    outputs = []
    
    if method == "otu" or method == "qiime2" or method == "vsearch" or method == "operational_taxonomic_units":
        return expand(
            f"{RESULTS_DIR}/rRNA/{{sample}}/sortmerna/{{stage}}/{{sample}}_{{stage}}.aligned_fwd.fq.gz",
            zip,
            sample=SAMPLES,
            stage=FINAL_SORTMERNA_STAGE,
        )
    elif method == "asv" or method == "dada2" or method == "amplicon" or method == "amplicon_sequence_variants":
        return expand(
            f"{RESULTS_DIR}/rRNA/{{sample}}/sortmerna/{{stage}}/{{sample}}_{{stage}}.aligned_fwd.fq.gz",
            zip,
            sample=SAMPLES,
            stage=FINAL_SORTMERNA_STAGE,
        )
    elif method in ["kraken2", "bracken", "taxonomic_composition"]:
        outputs +=  expand(
            f"{RESULTS_DIR}/rRNA/{{sample}}/classification/{{sample}}.k2report",
            zip,
            sample=SAMPLES
        )
        outputs += expand(
            f"{RESULTS_DIR}/rRNA/{{sample}}/classification/{{sample}}.bracken.k2report",
            zip,
            sample=SAMPLES
        )
        outputs += expand(f"{RESULTS_DIR}/rRNA/taxonomy/bracken_species.biom")
        outputs += expand(f"{RESULTS_DIR}/rRNA/taxonomy/bracken_species_qualitative.txt")
        outputs += expand(f"{RESULTS_DIR}/rRNA/taxonomy/bracken_species_observations.txt")
        outputs += expand(f"{RESULTS_DIR}/rRNA/taxonomy/bracken_species.tsv")
        outputs += expand(f"{RESULTS_DIR}/rRNA/taxonomy/phyloseq.rds")
        return outputs
    else:
        raise ValueError(f"Unsupported RNA method: {method}")


# --------------------------
# Final target
# --------------------------

rule all:
    input:
        f"{RESULTS_DIR}/qc/QC.done",
        f"{RESULTS_DIR}/RNA/RNA_seperation.done",
        f"{RESULTS_DIR}/rRNA/rRNA.done"

# --------------------------
# Modules
# --------------------------

### Quality control and decontamination
include: "qc/rules/fastqc.smk"
include: "qc/rules/fastp.smk"
include: "qc/rules/bwa_decontamination.smk"

### RNA SEPERATION - check if the if statements are redudnant with the ones in the included rules (smk files) or if they are needed to avoid including rules that would not be used
if config["RNA"]["method"] == "sortmerna":
    if config["RNA"]["refinement"] == "staged":
        include: "RNA/rules/sortmerna_stages.smk"
        include: "RNA/rules/sortmerna_stages_postprocessing.smk"
    if config["RNA"]["refinement"] == "combined":
        include: "RNA/rules/sortmerna_combined.smk"
        include: "RNA/rules/sortmerna_combined_postprocessing.smk"
elif config["RNA"]["method"] == "ribodetector":
    include: "RNA/rules/ribodetector.smk"
    if config["RNA"]["refinement"] == "bbduk":
        include: "RNA/rules/bbduk.smk"
elif config["RNA"]["method"] == "bbmap":
    include: "RNA/rules/bbmap.smk"
    include: "RNA/rules/bbmap_postprocessing.smk"

### rRNA composition classification
#include: "rRNA/rules/qiime2.smk"
include: "rRNA/rules/kraken.smk"
include: "rRNA/rules/bracken.smk"
include: "rRNA/rules/kraken_bracken_downstream.smk"

# once the rules has been completed check 
# --------------------------
# Final targets
# --------------------------
rule QC_done:
    input:
        qc_outputs(RESULTS_DIR, SAMPLES)
    output:
        flag=f"{RESULTS_DIR}/qc/QC.done"
    shell:
        """
        mkdir -p {RESULTS_DIR}/qc
        touch {output.flag}
        """

rule RNA_seperation_done:
    input:
        RNA_separation_module()
    output:
        flag=f"{RESULTS_DIR}/RNA/RNA_seperation.done"
    shell:
        """
        mkdir -p {RESULTS_DIR}/RNA
        touch {output.flag}
        """

rule rRNA_done:
    input:
        rRNA_composition_method()
    output:
        flag=f"{RESULTS_DIR}/rRNA/rRNA.done"
    shell:
        """
        mkdir -p {RESULTS_DIR}/rRNA
        touch {output.flag}
        """

# snakemake --use-conda --conda-prefix /data_2/rasmus/snakemake-conda --cores 35 --rerun-incomplete --keep-going