
# Databases: absolute paths
# Silvamod or Greengenes reference databases, for example silvamod138pr2.fasta
BLAST_DATABASE: "<custom_dir>/silvamod138pr2.fasta"
# Small ribosome subunit database such as SILVA_138.1_SSURef
SORTMERNA_SSU_REF_DATABASE: "<custom_dir>/SILVA_138.1_SSURef"
# Large ribosome subunit database such as SILVA_138.1_SSURef
SORTMERNA_LSU_REF_DATABASE: "<custom_dir>/SILVA_138.1_SSURef"
# Index cache for sortmerna
# Sortmerna will save the index in those directories to avoid computing them again and again
# Please, create an empty directory (one for each)
SORTMERNA_SSU_DATABASE_INDEX: "<custom_dir>"
SORTMERNA_LSU_DATABASE_INDEX: "<custom_dir>"
# When annotating rRNA, CREST4 will download Silva 138 in the following path
CREST4_DIR: "~/.crest4/"
#Next variables point to any database you want to use for functional analysis
#Diamond will your mRNA against those. The pipeline expects all databases in a single directory
DIAMOND_DATABASES_DIR: "<custom_dir>"
#The filename without extension of a valid diamond database
#The pipeline will run only those you add here
DIAMOND_DATABASES_IDENTIFIER:
  - "<fake_database>"
#Next variables points to each of the 3 available databases in CoMW (Md5nr, CAZy and NCyC)
# that you have installed with CoMW
SWORD_DATABASES:
  - Md5nr: "<custom_dir>/file.fasta"
  - CAZy: "<custom_dir>/file.fasta"
  - NCyc: "<custom_dir>/file.fasta"

PRIVATE_METARIB: 
  # Database for EMIRGE such us SILVA_138.1_SSURef 
  - EM_REF : "<custom_dir>/SILVA_138.1_SSURef "
  # Index cache for Emirge reference
  # Metarib will save the index in those directories to avoid computing them again and again
  # Please, create an empty directory
  - EM_BT : "<custom_dir>"