
SORTMERNA_SSU_REF_DATABASE: "/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.fasta"
SORTMERNA_LSU_REF_DATABASE: "/Databases/SILVA_138/SILVA_138.1_LSURef_NR99_tax_silva_trunc.fasta"
SORTMERNA_SSU_DATABASE_INDEX: "/Databases/sortmerna_idx/SSU"
SORTMERNA_LSU_DATABASE_INDEX: "/Databases/sortmerna_idx/LSU"

RFAM_DATABASE: "/software/CoMW/databases/Rfam.cm"

# When annotating rRNA, CREST4 will download Silva 138 in the following path
CREST4_DIR: "/Databases/CREST4_DB/"

PRIVATE_METARIB: 
  # EMIRGE references 
  - EM_REF : "/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta"
  # EMIRGE reference index
  - EM_BT : "/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed"