# Databases: absolute paths
# Silvamod or Greengenes reference databases, for example silvamod138pr2.fasta
BLAST_DATABASE: ""
# Small ribosome subunit database such as SILVA_138.1_SSURef
SORTMERNA_SSU_REF_DATABASE: ""
# Large ribosome subunit database such as SILVA_138.1_SSURef
SORTMERNA_LSU_REF_DATABASE: ""
# Index cache for sortmerna
# Sortmerna will save the index in those directories to avoid computing them again and again
# Please, create an empty directory (one for each)
SORTMERNA_SSU_DATABASE_INDEX: ""
SORTMERNA_LSU_DATABASE_INDEX: ""

# This pipeline have 2 dependencies which are not handle automatically
# Please, install CREST as follows
# https://github.com/lanzen/CREST#installation
# Next variable handles the classify binary file (something like CREST/LCAClassifier/bin/classify)
CREST_LCAClassifier_BINARY: ""
# Please, install CREST as follows
# https://github.com/lanzen/CREST#installation
# Next variable handles the classify binary file (something like CREST/LCAClassifier/bin/classify)
# Please, install CoMW as follows
https://github.com/currocam/CoMW#system-requirement-structure-and-installation
# Please, be aware this is a temporary solution
# Next variable points to the CoMW directory (wherever you cloned it)
CoMW_REPOSITORY: ""
#Next variables points to each of the 3 available databases in CoMW (Md5nr, CAZy and NCyC)
# that you have installed with CoMW
SWORD_DATABASES:
  - Md5nr: ""
  - CAZy: ""
  - NCyc: ""


PRIVATE_METARIB: 
  # Database for EMIRGE such us SILVA_138.1_SSURef 
  - EM_REF : ""
  # Index cache for Emirge reference
  # Metarib will save the index in those directories to avoid computing them again and again
  # Please, create an empty directory
  - EM_BT : ""
