SORTMERNA_SSU_REF_DATABASE: "/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.fasta"
SORTMERNA_LSU_REF_DATABASE: "/Databases/SILVA_138/SILVA_138.1_LSURef_NR99_tax_silva_trunc.fasta"
#BLAST_DATABASE: "/software/CREST/LCAClassifier/parts/flatdb/silvamod/silvamod128.fasta"
BLAST_DATABASE: "/Databases/SilvaMod138PR2/silvamod138pr2.fasta"
CREST_LCAClassifier_BINARY: "/software/CREST/LCAClassifier/bin/classify"
CoMW_REPOSITORY: "/software/CoMW/"
PRIVATE_METARIB: 
  # EMIRGE references 
  - EM_REF : "/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta"
  # EMIRGE reference index
  - EM_BT : "/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed"
