samples_file: /data/rasmus/TotalRNA-Snakemake/dataset/samplesheet.tsv

databases:
  human_GRCh38_genome: /data_2/Databases/GRCh38/GCF_000001405.40_GRCh38.p14_genomic.fna
  human_T2T_genome: /data_2/Databases/T2T‑CHM13/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna
  chloroplast_genome: /data_2/Databases/plant_organelle/refseq_chloroplast.fna 
  mitochondrion_genome: /data_2/Databases/mitochondrion/mitochondrion.1.1.genomic.fna
  genome_for_decontamination: /data_2/Databases/Contamination/GRCH38genomeMT_mitochondrion_organalle.fna
  sortmeRNA_ssu: /data_2/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.fasta
  sortmeRNA_ssu_idx: /data_2/Databases/sortmerna_idx/SSU/
  sortmeRNA_lsu: /data_2/Databases/SILVA_138/SILVA_138.1_LSURef_NR99_tax_silva_trunc.fasta
  sortmeRNA_lsu_idx: /data_2/Databases/sortmerna_idx/LSU/
  crest4_db: /data_2/Databases/crest4/silvamod138pr2
  kraken_db: /data_2/Databases/kraken2_dbs

# decontamination_sources: #combine human, chloroplast, mitochondrion or somethign

#######################
### Module settings ###
#######################

qc:
  fastqc:
    threads: 2
  fastp:
    options: "--detect_adapter_for_pe --length_required 60 --cut_right --cut_right_window_size 5 --cut_mean_quality 20 --trim_poly_g --trim_poly_x --poly_x_min_len 10"
    threads: 8
  kraken2:
    options: "--confidence 0.1 --use-names"
    threads: 10
  bwa_contaminants:
    threads: 16
  contamination_source_ids:
    options: -f 2 -q 30 -l 50 -r 0.5
  decontamination:
    threads: 8
  sortmerna:
    options: "--fastx --other --paired_in --out2"
    threads: 12
    pipeline:
      - ssu
      - lsu
  
#rRNA:
#  Metarib
#  .
#  .

#nonrRNA:
#  Trinity
#  .
#  .