samples_file: /data/rasmus/TotalRNA-Snakemake/dataset/samplesheet.tsv

databases:
  human_genome: /data_2/Databases/Human_genome/GRCh38.p13.genome.fa #example
  sortmeRNA_ssu: /data_2/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.fasta
  sortmeRNA_lsu: /data_2/Databases/SILVA_138/SILVA_138.1_LSURef_NR99_tax_silva_trunc.fasta
  crest4_db: /data_2/Databases/crest4/silvamod138pr2

#######################
### Module settings ###
#######################

qc:
  fastqc:
    threads: 8
  fastp:
    options: "--detect_adapter_for_pe --length_required 60 --cut_right --cut_right_window_size 5 --cut_mean_quality 20 --trim_poly_g --trim_poly_x --poly_x_min_len 10"
    threads: 8
