#samples_file: /data/rasmus/Dev/Lucas/samplesheet.tsv
samples_file: /data/rasmus/TotalRNA-Snakemake/dataset/samplesheet.tsv

shared_results_dir: /data/rasmus/Dev/SnakeResDev

ncbi_email: "au811884.uni.au.dk"
send_mail: "yes"

databases:
  human_GRCh38_genome: /data_2/Databases/GRCh38/GCF_000001405.40_GRCh38.p14_genomic.fna
  human_T2T_genome: /data_2/Databases/T2T‑CHM13/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna
  chloroplast_genome: /data_2/Databases/plant_organelle/refseq_chloroplast.fna 
  mitochondrion_genome: /data_2/Databases/mitochondrion/mitochondrion.1.1.genomic.fna
  genome_for_decontamination: /data_2/Databases/Contamination/GRCH38genomeMT_mitochondrion_organalle.fna
  sortmeRNA_ssu: /data_2/Databases/SILVA_138/SILVA_138.1_SSURef_NR99_tax_silva_trunc.fasta
  sortmeRNA_lsu: /data_2/Databases/SILVA_138/SILVA_138.1_LSURef_NR99_tax_silva_trunc.fasta
  sortmeRNA_ssu_lsu: /data_2/Databases/SILVA_138/SILVA_138.1_LSU_SSU_Ref_NR99_tax_silva_trunc.fasta
  sortmeRNA_ssu_idx: /data_2/Databases/sortmerna5_idx/SSU/idx/
  sortmeRNA_lsu_idx: /data_2/Databases/sortmerna5_idx/LSU/idx/
  sortmeRNA_ssu_lsu_idx: /data_2/Databases/sortmerna5_idx/SSU_LSU/idx/
  sortmeRNA_ssu_ids: /data_2/Databases/sortmerna_idx/SSU/SILVA_138.1_SSURef_NR99_tax_silva_trunc.contigs_ids
  SILVA_138.1_N99: /data_2/Databases/SILVA_138/SILVA_138.1_SSU_LSU_N99_tax_silva_trunc.fasta
  SILVA_138.2_N99_blast: /data_2/Databases/SILVA_138.2_blast/SILVA_138.2_SSURef_NR99
  crest4_db: /data_2/Databases/crest4/silvamod138pr2
  kraken_decontamination_db: /data_2/Databases/kraken2_dbs
  kraken_rRNA_db: /data_2/Databases/silva_kraken_db/SILVA_138_2_k2db
  taxonomy_table: /data_2/Databases/taxonomy/taxonomy.tsv
  humann_bowtie2db: /data_2/Databases/humann/metaphlan/
  humann_nucleotidedb: /data_2/Databases/humann/chocophlan/
  humann_proteindb: /data_2/Databases/humann/uniref/
  diamond_proteindb: /data_2/Databases/uniref90_db/uniref90.dmnd
  Pfam_db: /data_2/Databases/Pfam/Pfam-A.hmm
  emapper_diamond_proteindb: /data_2/Databases/eggnog_mapper
  phyloflash: /data_2/Databases/phyloflash/138.2

#######################
### Module settings ###
#######################

qc:
  fastqc:
    threads: 2
  fastp:
    options: "--detect_adapter_for_pe --length_required 60 --cut_right --cut_right_window_size 5 --cut_mean_quality 20 --trim_poly_g --trim_poly_x --poly_x_min_len 10"
    threads: 8
  bwa_contaminants:
    threads: 16
  contamination_source_ids:
    options: -f 2 -q 30 -l 50 -r 0.5
  decontamination:
    threads: 8

RNA:
  method: ribodetector # sortmerna | ribodetector | bbmap | other methods to be added in the future, e.g. based on mapping or something else
  refinement: bbduk #staged | combined | bbduk (refinement of ribodetector output, e.g. to get more rRNA reads or to get higher confidence rRNA reads)
  # Seperation of rRNA from non-rRNA reads using sortmerna, either in a staged manner (first separate SSU and then LSU) or in a combined manner (SSU and LSU together)
  threads: 6
  sortmerna_staged:
    options: "--fastx --paired_in --out2 --id 0.97 --coverage 0.97 --index 0 --dbg-level 2" # should we add the 0.97 identity as well to ensure if we change in the rRNA section, then the sortmerna created OTU would be comparable to the qiime2 created OTU?
    threads: 16
    pipeline:
      - ssu
      - lsu
  sortmerna_combined:
    options: "--sam --SQ --print_all_reads --zip-out 0 --min_lis 3 --num_seeds 3 -e 1e-3 --max_pos 500"
    threads: 16
  # rRNA filtration method based on ribodetector, which is a tool that uses a combination of k-mer based and alignment based methods to identify rRNA reads. Consider adding additional refinement steps, e.g. using bbduk or bbmap to get more rRNA reads or to get higher confidence rRNA reads.
  ribodetector:
    options: "--ensure rrna"
    threads: 15
  bbduk:
    options: "k=31 ordered=t hdist=1"
    threads: 8
  # General alignment based method for rRNA read refinement, which can be used to get more rRNA reads or to get higher confidence rRNA reads. Consider adding additional options, e.g. minid, maxindel, etc.
  bbmap:
    options: "minid=0.90 ambiguous=best unpigz=t maxindel=100 minhits=2" # consider adding minhits, and increase the minid, or look into additional reads
    threads: 16

rRNA:
  method: kraken2        # kraken2 + bracken (taxonomic classification)
  kraken2:
    threads: 10
  bracken:
    options: "-r 150 -l G -t 10"
  kraken_biom:
    options: "--min G --max D --fmt hdf5"

nonrRNA:
  nonrrna_module: coassembly # read | coassembly | assembly | both | all
  read_method: humann # humann | metaphlan
  assembly_method: spades # spades | rnaspades | trinity
  assembly_predictor: transdecoder #prodigal | transdecoder
  threads: 24
  metaphlan:
    threads: 14
    options: "--input_type fastq --index mpa_vJun23_CHOCOPhlAnSGB_202307 --add_viruses" #the index here is directly related to the humann_bowtie2dbs database used for metaphlan
  humann:
    threads: 3
    options: "--diamond-options=--fast --prescreen-threshold 0.05 --translated-query-coverage-threshold 50"
  rnaspades:
    threads: 16
    options: "--rna"
  diamond_blastp:
    threads: 24
    options: "--outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore --evalue 1e-5 --max-target-seqs 1 --sensitive"
  hmmscan:
    threads: 3
    chunk_size: 50000
    options: "--cut_ga --noali --acc"
  transdecoder:
    options: "-m 100"
  prodigal:
    options: "-p meta -f gff -m -c -n"
  eggnog:
    threads: 24
    options: "--itype proteins -m diamond --sensmode sensitive"
  salmon:
    threads: 12
  
phylogeny:
  reconstruction_method: phyloflash
  secondary: PR2
  phyloflash:
    threads: 12
    options: "-nokeeptmp -nozip"
  blastn:
    threads: 12
    options: '-outfmt "6 qseqid sseqid pident length qlen slen qcovs evalue bitscore stitle" -evalue 1e-20 -max_target_seqs 100 -max_hsps 1'
  blastn_postprocessing:
    top_n_hits: 20
    nt_identify: 97
    query_coverage: 90
  mafft:
    threads: 6
  iqtree:
    threads: 12
    options: "-m MFP -B 1000 -alrt 1000"